import { SupordoHeader } from "./SupordoHeader";
import { SupordoHero } from "./SupordoHero";

/**
 * The SUPORDO brand landing, served at "/" on the platform host only
 * (supordo.com / www.supordo.com — see __root.tsx beforeLoad). A tenant
 * hostname never reaches this component: its "/" still renders the artisan
 * site exactly as before.
 *
 * .supordo-brand scopes the SUPORDO tokens and Manrope to this subtree, so
 * the brand's visual language never becomes the design system of the artisan
 * sites generated by the platform.
 *
 * Header + Hero only for this iteration — no other section.
 */
export function SupordoLanding() {
  return (
    <div className="supordo-brand min-h-screen bg-[var(--supordo-warm)] antialiased">
      <SupordoHeader />
      <main>
        <SupordoHero />
      </main>
    </div>
  );
}
