import { SupordoHeader } from "./SupordoHeader";
import { SupordoHero } from "./SupordoHero";
import { SupordoTrades } from "./SupordoTrades";
import { SupordoActThree } from "./SupordoActThree";
import { SupordoActFive } from "./SupordoActFive";
import { SupordoActSix } from "./SupordoActSix";
import { SupordoActSeven } from "./SupordoActSeven";
import { SupordoFooter } from "./SupordoFooter";

/**
 * The SUPORDO brand landing, served at "/" on the platform host only
 * (supordo.com / www.supordo.com — see __root.tsx beforeLoad). A tenant
 * hostname never reaches this component: its "/" still renders the artisan
 * site exactly as before.
 *
 * .supordo-brand scopes the SUPORDO tokens and Manrope to this subtree, so
 * the brand's visual language never becomes the design system of the artisan
 * sites generated by the platform.
 *
 * leadIntakeReady comes from the route loader: it is true only when a request
 * sent from /demarrer really reaches SUPORDO. Every call to action in this
 * tree (header, hero, Act 6, Act 7) follows it, so no visible button can
 * lead to a page that would lose the visitor's request.
 *
 * Act 4 (SupordoActFour) is deliberately not mounted here: it needs a
 * selected, authorized EASYDEP réalisation and real captures that don't
 * exist yet (plan §22). Kept in the repo, ready to insert between Act 3 and
 * Act 5 once those are available.
 */
export function SupordoLanding({ leadIntakeReady = false }: { leadIntakeReady?: boolean }) {
  return (
    <div className="supordo-brand min-h-screen bg-[var(--supordo-warm)] antialiased">
      <SupordoHeader leadIntakeReady={leadIntakeReady} />
      <main>
        <SupordoHero leadIntakeReady={leadIntakeReady} />
        <SupordoTrades />
        <SupordoActThree />
        <SupordoActFive />
        <SupordoActSix leadIntakeReady={leadIntakeReady} />
        <SupordoActSeven leadIntakeReady={leadIntakeReady} />
      </main>
      <SupordoFooter />
    </div>
  );
}
