import { SupordoHeader } from "./SupordoHeader";
import { SupordoHero } from "./SupordoHero";
import { SupordoTrades } from "./SupordoTrades";
import { SupordoActThree } from "./SupordoActThree";
import { SupordoActFive } from "./SupordoActFive";
import { SupordoFooter } from "./SupordoFooter";

/**
 * The SUPORDO brand landing, served at "/" on the platform host only
 * (supordo.com / www.supordo.com — see __root.tsx beforeLoad). A tenant
 * hostname never reaches this component: its "/" still renders the artisan
 * site exactly as before.
 *
 * .supordo-brand scopes the SUPORDO tokens and Manrope to this subtree, so
 * the brand's visual language never becomes the design system of the artisan
 * sites generated by the platform.
 *
 * leadIntakeReady comes from the route loader: it is true only when a request
 * sent from /demarrer really reaches SUPORDO. The header and hero calls to
 * action follow it, so no visible button can lead to a page that would lose
 * the visitor's request.
 */
export function SupordoLanding({ leadIntakeReady = false }: { leadIntakeReady?: boolean }) {
  return (
    <div className="supordo-brand min-h-screen bg-[var(--supordo-warm)] antialiased">
      <SupordoHeader leadIntakeReady={leadIntakeReady} />
      <main>
        <SupordoHero leadIntakeReady={leadIntakeReady} />
        <SupordoTrades />
        <SupordoActThree />
        <SupordoActFive />
      </main>
      <SupordoFooter />
    </div>
  );
}
