/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as DemarrerIndexRouteImport } from './routes/demarrer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SuperAdminTenantsRouteImport } from './routes/super-admin.tenants'
import { Route as SuperAdminOnboardingRouteImport } from './routes/super-admin.onboarding'
import { Route as SuperAdminMediaLibraryRouteImport } from './routes/super-admin.media-library'
import { Route as SuperAdminBrandsRouteImport } from './routes/super-admin.brands'
import { Route as ServicesServiceSlugRouteImport } from './routes/services.$serviceSlug'
import { Route as DemarrerConfirmationRouteImport } from './routes/demarrer.confirmation'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminServiceAreasRouteImport } from './routes/admin.service-areas'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminBrandsRouteImport } from './routes/admin.brands'
import { Route as SuperAdminTenantsIndexRouteImport } from './routes/super-admin.tenants.index'
import { Route as SuperAdminTenantsTenantIdRouteImport } from './routes/super-admin.tenants.$tenantId'
import { Route as SuperAdminTenantsTenantIdMediaRouteImport } from './routes/super-admin.tenants.$tenantId.media'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const DemarrerIndexRoute = DemarrerIndexRouteImport.update({
  id: '/demarrer/',
  path: '/demarrer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminTenantsRoute = SuperAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminOnboardingRoute = SuperAdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminMediaLibraryRoute = SuperAdminMediaLibraryRouteImport.update({
  id: '/media-library',
  path: '/media-library',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminBrandsRoute = SuperAdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => SuperAdminRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: '/$serviceSlug',
  path: '/$serviceSlug',
  getParentRoute: () => ServicesRoute,
} as any)
const DemarrerConfirmationRoute = DemarrerConfirmationRouteImport.update({
  id: '/demarrer/confirmation',
  path: '/demarrer/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServiceAreasRoute = AdminServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrandsRoute = AdminBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AdminRoute,
} as any)
const SuperAdminTenantsIndexRoute = SuperAdminTenantsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminTenantsRoute,
} as any)
const SuperAdminTenantsTenantIdRoute =
  SuperAdminTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => SuperAdminTenantsRoute,
  } as any)
const SuperAdminTenantsTenantIdMediaRoute =
  SuperAdminTenantsTenantIdMediaRouteImport.update({
    id: '/media',
    path: '/media',
    getParentRoute: () => SuperAdminTenantsTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demarrer/confirmation': typeof DemarrerConfirmationRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/super-admin/brands': typeof SuperAdminBrandsRoute
  '/super-admin/media-library': typeof SuperAdminMediaLibraryRoute
  '/super-admin/onboarding': typeof SuperAdminOnboardingRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/demarrer/': typeof DemarrerIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/super-admin/tenants/$tenantId': typeof SuperAdminTenantsTenantIdRouteWithChildren
  '/super-admin/tenants/': typeof SuperAdminTenantsIndexRoute
  '/super-admin/tenants/$tenantId/media': typeof SuperAdminTenantsTenantIdMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/update-password': typeof UpdatePasswordRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demarrer/confirmation': typeof DemarrerConfirmationRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/super-admin/brands': typeof SuperAdminBrandsRoute
  '/super-admin/media-library': typeof SuperAdminMediaLibraryRoute
  '/super-admin/onboarding': typeof SuperAdminOnboardingRoute
  '/admin': typeof AdminIndexRoute
  '/demarrer': typeof DemarrerIndexRoute
  '/services': typeof ServicesIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/super-admin/tenants/$tenantId': typeof SuperAdminTenantsTenantIdRouteWithChildren
  '/super-admin/tenants': typeof SuperAdminTenantsIndexRoute
  '/super-admin/tenants/$tenantId/media': typeof SuperAdminTenantsTenantIdMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/realisations': typeof RealisationsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/update-password': typeof UpdatePasswordRoute
  '/admin/brands': typeof AdminBrandsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/service-areas': typeof AdminServiceAreasRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/demarrer/confirmation': typeof DemarrerConfirmationRoute
  '/services/$serviceSlug': typeof ServicesServiceSlugRoute
  '/super-admin/brands': typeof SuperAdminBrandsRoute
  '/super-admin/media-library': typeof SuperAdminMediaLibraryRoute
  '/super-admin/onboarding': typeof SuperAdminOnboardingRoute
  '/super-admin/tenants': typeof SuperAdminTenantsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/demarrer/': typeof DemarrerIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/super-admin/tenants/$tenantId': typeof SuperAdminTenantsTenantIdRouteWithChildren
  '/super-admin/tenants/': typeof SuperAdminTenantsIndexRoute
  '/super-admin/tenants/$tenantId/media': typeof SuperAdminTenantsTenantIdMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/accept-invite'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/mentions-legales'
    | '/realisations'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/super-admin'
    | '/update-password'
    | '/admin/brands'
    | '/admin/contacts'
    | '/admin/partners'
    | '/admin/portfolio'
    | '/admin/service-areas'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/demarrer/confirmation'
    | '/services/$serviceSlug'
    | '/super-admin/brands'
    | '/super-admin/media-library'
    | '/super-admin/onboarding'
    | '/super-admin/tenants'
    | '/admin/'
    | '/demarrer/'
    | '/services/'
    | '/super-admin/'
    | '/super-admin/tenants/$tenantId'
    | '/super-admin/tenants/'
    | '/super-admin/tenants/$tenantId/media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/accept-invite'
    | '/contact'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/mentions-legales'
    | '/realisations'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/update-password'
    | '/admin/brands'
    | '/admin/contacts'
    | '/admin/partners'
    | '/admin/portfolio'
    | '/admin/service-areas'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/demarrer/confirmation'
    | '/services/$serviceSlug'
    | '/super-admin/brands'
    | '/super-admin/media-library'
    | '/super-admin/onboarding'
    | '/admin'
    | '/demarrer'
    | '/services'
    | '/super-admin'
    | '/super-admin/tenants/$tenantId'
    | '/super-admin/tenants'
    | '/super-admin/tenants/$tenantId/media'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/accept-invite'
    | '/admin'
    | '/contact'
    | '/forgot-password'
    | '/llms.txt'
    | '/login'
    | '/mentions-legales'
    | '/realisations'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/super-admin'
    | '/update-password'
    | '/admin/brands'
    | '/admin/contacts'
    | '/admin/partners'
    | '/admin/portfolio'
    | '/admin/service-areas'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/team'
    | '/demarrer/confirmation'
    | '/services/$serviceSlug'
    | '/super-admin/brands'
    | '/super-admin/media-library'
    | '/super-admin/onboarding'
    | '/super-admin/tenants'
    | '/admin/'
    | '/demarrer/'
    | '/services/'
    | '/super-admin/'
    | '/super-admin/tenants/$tenantId'
    | '/super-admin/tenants/'
    | '/super-admin/tenants/$tenantId/media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  RealisationsRoute: typeof RealisationsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  DemarrerConfirmationRoute: typeof DemarrerConfirmationRoute
  DemarrerIndexRoute: typeof DemarrerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/demarrer/': {
      id: '/demarrer/'
      path: '/demarrer'
      fullPath: '/demarrer/'
      preLoaderRoute: typeof DemarrerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/tenants': {
      id: '/super-admin/tenants'
      path: '/tenants'
      fullPath: '/super-admin/tenants'
      preLoaderRoute: typeof SuperAdminTenantsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/onboarding': {
      id: '/super-admin/onboarding'
      path: '/onboarding'
      fullPath: '/super-admin/onboarding'
      preLoaderRoute: typeof SuperAdminOnboardingRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/media-library': {
      id: '/super-admin/media-library'
      path: '/media-library'
      fullPath: '/super-admin/media-library'
      preLoaderRoute: typeof SuperAdminMediaLibraryRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/brands': {
      id: '/super-admin/brands'
      path: '/brands'
      fullPath: '/super-admin/brands'
      preLoaderRoute: typeof SuperAdminBrandsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/services/$serviceSlug': {
      id: '/services/$serviceSlug'
      path: '/$serviceSlug'
      fullPath: '/services/$serviceSlug'
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/demarrer/confirmation': {
      id: '/demarrer/confirmation'
      path: '/demarrer/confirmation'
      fullPath: '/demarrer/confirmation'
      preLoaderRoute: typeof DemarrerConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/service-areas': {
      id: '/admin/service-areas'
      path: '/service-areas'
      fullPath: '/admin/service-areas'
      preLoaderRoute: typeof AdminServiceAreasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brands': {
      id: '/admin/brands'
      path: '/brands'
      fullPath: '/admin/brands'
      preLoaderRoute: typeof AdminBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/super-admin/tenants/': {
      id: '/super-admin/tenants/'
      path: '/'
      fullPath: '/super-admin/tenants/'
      preLoaderRoute: typeof SuperAdminTenantsIndexRouteImport
      parentRoute: typeof SuperAdminTenantsRoute
    }
    '/super-admin/tenants/$tenantId': {
      id: '/super-admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/super-admin/tenants/$tenantId'
      preLoaderRoute: typeof SuperAdminTenantsTenantIdRouteImport
      parentRoute: typeof SuperAdminTenantsRoute
    }
    '/super-admin/tenants/$tenantId/media': {
      id: '/super-admin/tenants/$tenantId/media'
      path: '/media'
      fullPath: '/super-admin/tenants/$tenantId/media'
      preLoaderRoute: typeof SuperAdminTenantsTenantIdMediaRouteImport
      parentRoute: typeof SuperAdminTenantsTenantIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBrandsRoute: typeof AdminBrandsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminServiceAreasRoute: typeof AdminServiceAreasRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBrandsRoute: AdminBrandsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminServiceAreasRoute: AdminServiceAreasRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SuperAdminTenantsTenantIdRouteChildren {
  SuperAdminTenantsTenantIdMediaRoute: typeof SuperAdminTenantsTenantIdMediaRoute
}

const SuperAdminTenantsTenantIdRouteChildren: SuperAdminTenantsTenantIdRouteChildren =
  {
    SuperAdminTenantsTenantIdMediaRoute: SuperAdminTenantsTenantIdMediaRoute,
  }

const SuperAdminTenantsTenantIdRouteWithChildren =
  SuperAdminTenantsTenantIdRoute._addFileChildren(
    SuperAdminTenantsTenantIdRouteChildren,
  )

interface SuperAdminTenantsRouteChildren {
  SuperAdminTenantsTenantIdRoute: typeof SuperAdminTenantsTenantIdRouteWithChildren
  SuperAdminTenantsIndexRoute: typeof SuperAdminTenantsIndexRoute
}

const SuperAdminTenantsRouteChildren: SuperAdminTenantsRouteChildren = {
  SuperAdminTenantsTenantIdRoute: SuperAdminTenantsTenantIdRouteWithChildren,
  SuperAdminTenantsIndexRoute: SuperAdminTenantsIndexRoute,
}

const SuperAdminTenantsRouteWithChildren =
  SuperAdminTenantsRoute._addFileChildren(SuperAdminTenantsRouteChildren)

interface SuperAdminRouteChildren {
  SuperAdminBrandsRoute: typeof SuperAdminBrandsRoute
  SuperAdminMediaLibraryRoute: typeof SuperAdminMediaLibraryRoute
  SuperAdminOnboardingRoute: typeof SuperAdminOnboardingRoute
  SuperAdminTenantsRoute: typeof SuperAdminTenantsRouteWithChildren
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminBrandsRoute: SuperAdminBrandsRoute,
  SuperAdminMediaLibraryRoute: SuperAdminMediaLibraryRoute,
  SuperAdminOnboardingRoute: SuperAdminOnboardingRoute,
  SuperAdminTenantsRoute: SuperAdminTenantsRouteWithChildren,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  RealisationsRoute: RealisationsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  UpdatePasswordRoute: UpdatePasswordRoute,
  DemarrerConfirmationRoute: DemarrerConfirmationRoute,
  DemarrerIndexRoute: DemarrerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
